# Expected structure of .pre-commit-config.yaml generated by fmtinit
# This template serves as documentation and reference only.

repos:
  # Black formatter
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  # Ruff linter/formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Prettier formatter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
